### ISSUE TITLE
[BugFix] Infinity loop RSS Feed

### ISSUE THREAD

**Issue by di3goleite** [devfsa/overflow-news#15]
See: [jlongster](https://jlongster.com/atom.xml)

**Comment by rafaelverger** [comment]
So, the error is this one?
```➜  overflow-news git:(master) ./node_modules/.bin/babel-node
> const job = require('./src/lib/job')
> job.crawlFeed('http://feedpress.me/jlongster', console.log)
[ERROR] Exceeded maxRedirects. Probably stuck in a redirect loop http://jlongster.com/atom.xml
Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://jlongster.com/atom.xml
    at Redirect.onResponse (/Users/rafaelverger/git-projects/overflow-news/node_modules/request/lib/redirect.js:98:27)
    at Request.onRequestResponse (/Users/rafaelverger/git-projects/overflow-news/node_modules/request/request.js:990:22)
    at ClientRequest.emit (events.js:127:13)
    at ClientRequest.emit (domain.js:439:23)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:444:20)
    at Socket.emit (events.js:127:13)
    at Socket.emit (domain.js:439:23)
    at addChunk (_stream_readable.js:269:12)
[ERROR] Not a feed
```

If it is, I can't see what need to be done here... an http requests ends up breaking due to maxRedirects. The worker code (that is using `crawlFeed` method) is prepared to [handle this error](https://github.com/di3goleite/overflow-news/blob/master/src/worker.js#L58-L72) so what is this issue's goal?

**Comment by di3goleite** [comment]
The main issue is: when this error happens the worker stops. I don't know what is happening but we need to move on when we face errors like that.

**Comment by RodolfoSilva** [comment]
I'll solve this issue @rafaelverger and @di3goleite

**Comment by di3goleite** [comment]
Hello @RodolfoSilva do you have any update about this issue?

**Comment by RodolfoSilva** [comment]
I can't reproduce the error, I'll try again later.

**Comment by di3goleite** [comment]
I cannot reproduce this error too. So, I'll close it.
